fileFormatVersion: 2
guid: d937f0ae4113443b78db34d7d15cd41b
DefaultImporter:
  externalObjects: {}
  userData: 
  assetBundleName: 
  assetBundleVariant: 
AssetOrigin:
  serializedVersion: 1
  productId: 336970
  packageName: FREE Starter Pack - Sidekick Modular Characters by Synty
  packageVersion: 1.0.1
  assetPath: Assets/Synty/SidekickCharacters/Plugins/unity-sqlite-net-1.2.4/Plugins/Makefile
  uploadId: 803948
